# Generated by Django 2.1.8 on 2019-04-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ailment',
            old_name='ailment',
            new_name='ailments',
        ),
    ]
